baseURL: https://cybersma.com/
languageCode: en-us
title: CYBERSMA
theme: PaperMod
params:
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true


menu:
  main:
    - name: Security
      url: /categories/Cyber Security/
      weight: 1
    - name: AI
      url: /categories/AI Data/
      weight: 2
    - name: Software
      url: /categories/Software Tool/
      weight: 3
    - name: Archives
      url: /archives/
      weight: 4  


