baseURL: https://cybersma.com/
languageCode: en-us
title: CYBERSMA
theme: PaperMod
params:
  ShowCodeCopyButtons: true
menu:
  main:
    - name: Security
      url: /categories/security/
      weight: 1
    - name: AI & Data
      url: /categories/ai-data/
      weight: 2
    - name: Software
      url: /categories/software/
      weight: 3
    - name: Archives
      url: /archives/
      weight: 4  


